// Family London — sightseeing & things to do data
// Each entry: id, name, emoji, category[], free, ageRange, desc, address, nearestTube, tubeColor, tubeLine, walkMins, cost, openingHours, tip

window.EXPLORE_DATA = [

  // ── FREE MUSEUMS ─────────────────────────────────────
  {
    id: 'nhm',
    name: 'Natural History Museum',
    emoji: '🦕',
    category: ['museum','free'],
    free: true,
    ageRange: 'All ages',
    desc: 'Dinosaur skeletons, a blue whale skeleton, the earthquake simulator — kids absolutely love it. Book timed entry online to skip the queue.',
    address: 'Cromwell Rd, SW7 5BD',
    nearestTube: 'South Kensington',
    tubeColor: '#003688',
    tubeLineName: 'Piccadilly / District',
    walkMins: 5,
    cost: 'Free',
    openingHours: 'Daily 10–17:50',
    tip: '🎯 Head straight to Dinosaurs gallery — queues build fast after 11am.'
  },
  {
    id: 'sciencemuseum',
    name: 'Science Museum',
    emoji: '🚀',
    category: ['museum','free'],
    free: true,
    ageRange: '4+',
    desc: 'Five floors of hands-on science, space rockets, a real Apollo 10 capsule, and the brilliant Wonderlab for younger children.',
    address: 'Exhibition Rd, SW7 2DD',
    nearestTube: 'South Kensington',
    tubeColor: '#003688',
    tubeLineName: 'Piccadilly / District',
    walkMins: 5,
    cost: 'Free (Wonderlab £12)',
    openingHours: 'Daily 10–18:00',
    tip: '🎯 Wonderlab booking essential. Same day as the NHM — they\'re 2 min apart.'
  },
  {
    id: 'britishmuseum',
    name: 'British Museum',
    emoji: '🏺',
    category: ['museum','free'],
    free: true,
    ageRange: '7+',
    desc: 'Eight million objects from across human history. The Rosetta Stone, Egyptian mummies, and the Elgin Marbles are perennial favourites.',
    address: 'Great Russell St, WC1B 3DG',
    nearestTube: 'Holborn / Tottenham Court Road',
    tubeColor: '#E1251B',
    tubeLineName: 'Central',
    walkMins: 7,
    cost: 'Free',
    openingHours: 'Daily 10–17:00 (Fri to 20:30)',
    tip: '🎯 Get the family trail leaflet at the entrance — keeps kids engaged.'
  },
  {
    id: 'victoria-albert',
    name: 'V&A Museum',
    emoji: '🎨',
    category: ['museum','free'],
    free: true,
    ageRange: 'All ages',
    desc: 'The world\'s greatest decorative arts museum with stunning architecture. The V&A Young Friends programme and activity backpacks keep kids busy.',
    address: 'Cromwell Rd, SW7 2RL',
    nearestTube: 'South Kensington',
    tubeColor: '#003688',
    tubeLineName: 'Piccadilly / District',
    walkMins: 5,
    cost: 'Free',
    openingHours: 'Daily 10–17:45 (Fri to 22:00)',
    tip: '🎯 Combine with NHM — they\'re right next door. Hit the café in the gorgeous garden courtyard.'
  },
  {
    id: 'tate-modern',
    name: 'Tate Modern',
    emoji: '🖼️',
    category: ['museum','free'],
    free: true,
    ageRange: '8+',
    desc: 'World-class modern art in a converted power station. The Turbine Hall always has something spectacular installed, plus amazing Thames views from the top.',
    address: 'Bankside, SE1 9TG',
    nearestTube: 'Southwark / Blackfriars',
    tubeColor: '#003366',
    tubeLineName: 'Jubilee / District',
    walkMins: 10,
    cost: 'Free (special exhibitions extra)',
    openingHours: 'Sun–Thu 10–18:00, Fri–Sat 10–22:00',
    tip: '🎯 Walk across the Millennium Bridge to St Paul\'s Cathedral for a brilliant afternoon combo.'
  },
  {
    id: 'national-gallery',
    name: 'National Gallery',
    emoji: '🖼️',
    category: ['museum','free'],
    free: true,
    ageRange: '6+',
    desc: 'Over 2,300 paintings from the 13th to 19th century. Trafalgar Square is right outside — great for a rest and feeding the pigeons.',
    address: 'Trafalgar Square, WC2N 5DN',
    nearestTube: 'Charing Cross',
    tubeColor: '#007229',
    tubeLineName: 'Northern / Bakerloo',
    walkMins: 3,
    cost: 'Free',
    openingHours: 'Daily 10–18:00 (Fri to 21:00)',
    tip: '🎯 Kids\' Trail sheets at the info desk make it interactive. Great café too.'
  },
  {
    id: 'museum-london',
    name: 'Museum of London Docklands',
    emoji: '⚓',
    category: ['museum','free'],
    free: true,
    ageRange: '5+',
    desc: 'London\'s history from Roman times to today, set in a Georgian warehouse on the Docklands. Brilliant Mudlarks play area for little ones.',
    address: 'West India Quay, E14 4AL',
    nearestTube: 'West India Quay (DLR)',
    tubeColor: '#00A4A7',
    tubeLineName: 'DLR',
    walkMins: 2,
    cost: 'Free',
    openingHours: 'Daily 10–18:00',
    tip: '🎯 Mudlarks gallery is brilliant for under-8s. Combine with a Thames Clipper ride.'
  },

  // ── PAID ATTRACTIONS ─────────────────────────────────
  {
    id: 'tower-london',
    name: 'Tower of London',
    emoji: '🏰',
    category: ['attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'Crown Jewels, Beefeater tours, medieval armour, and real ravens. One of the most dramatic historic sites in Britain — genuinely unmissable.',
    address: 'Tower Hill, EC3N 4AB',
    nearestTube: 'Tower Hill',
    tubeColor: '#007229',
    tubeLineName: 'Circle / District',
    walkMins: 3,
    cost: '£34 adults / £17 children',
    openingHours: 'Tue–Sat 9–17:30, Sun–Mon 10–17:30',
    tip: '🎯 Book online to save money. Go Tuesday–Thursday to avoid weekend crowds.'
  },
  {
    id: 'london-eye',
    name: 'London Eye',
    emoji: '🎡',
    category: ['attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'A 30-minute slow rotation on the South Bank with 25-mile views across London. Spectacular at golden hour or twilight.',
    address: 'South Bank, SE1 7PB',
    nearestTube: 'Waterloo / Westminster',
    tubeColor: '#003366',
    tubeLineName: 'Jubilee / Bakerloo',
    walkMins: 10,
    cost: '£28–36 (book ahead for best price)',
    openingHours: 'Daily from 10:00',
    tip: '🎯 Buy a Fast Track ticket — standard queues can be 1+ hour in summer.'
  },
  {
    id: 'sea-life',
    name: 'SEA LIFE London Aquarium',
    emoji: '🦈',
    category: ['attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'Sharks, rays, jellyfish, and a brilliant penguin enclosure. One of Europe\'s largest aquariums, right next to the London Eye on the South Bank.',
    address: 'County Hall, SE1 7PB',
    nearestTube: 'Waterloo / Westminster',
    tubeColor: '#003366',
    tubeLineName: 'Jubilee',
    walkMins: 10,
    cost: '£28 adults / £23 children (book online)',
    openingHours: 'Daily 10–18:00',
    tip: '🎯 Combo with the London Eye for a South Bank day out. Book online — 30% cheaper.'
  },
  {
    id: 'harry-potter',
    name: 'Harry Potter Studio Tour',
    emoji: '⚡',
    category: ['attraction','show'],
    free: false,
    ageRange: '5+',
    desc: 'Walk through actual sets from the films — the Great Hall, Diagon Alley, the Forbidden Forest, and Hogwarts model. Allow at least 3–4 hours.',
    address: 'Studio Tour Drive, WD25 7LR (Watford)',
    nearestTube: 'Watford Junction (train from Euston)',
    tubeColor: '#007229',
    tubeLineName: 'Overground + shuttle bus',
    walkMins: 0,
    cost: '£53 adults / £43 children',
    openingHours: 'Daily — timed entry slots',
    tip: '🎯 Book MONTHS in advance. Get the Butterbeer at 10am before the queue builds.'
  },
  {
    id: 'kew-gardens',
    name: 'Kew Gardens',
    emoji: '🌿',
    category: ['outdoor','attraction'],
    free: false,
    ageRange: 'All ages',
    desc: '326 acres of stunning gardens, the Treetop Walkway, giant glasshouses, and a brilliant children\'s play area. UNESCO World Heritage Site.',
    address: 'Richmond, TW9 3AE',
    nearestTube: 'Kew Gardens',
    tubeColor: '#007229',
    tubeLineName: 'District',
    walkMins: 5,
    cost: '£22 adults / £9 children',
    openingHours: 'Daily 10:00 (closing varies)',
    tip: '🎯 Perfect full-day trip. Pack a picnic — café prices are steep.'
  },
  {
    id: 'zoo',
    name: 'ZSL London Zoo',
    emoji: '🦁',
    category: ['outdoor','attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'Over 750 species in the heart of Regent\'s Park. Gorillas, giraffes, tigers, and an incredible Land of the Lions exhibit. Lions IN London!',
    address: "Outer Circle, Regent's Park, NW1 4RY",
    nearestTube: 'Camden Town',
    tubeColor: '#000000',
    tubeLineName: 'Northern',
    walkMins: 15,
    cost: '£35 adults / £25 children (online)',
    openingHours: 'Daily 10:00–17:00',
    tip: '🎯 Book online for the daily keeper talks — included in admission. Meerkats at 11am!'
  },

  // ── OUTDOOR ─────────────────────────────────────────
  {
    id: 'hyde-park',
    name: 'Hyde Park & Diana Memorial',
    emoji: '🌳',
    category: ['outdoor','free'],
    free: true,
    ageRange: 'All ages',
    desc: 'London\'s most famous park with the Diana Memorial Fountain (kids wade in it in summer), a huge playground, and Serpentine lido.',
    address: 'W2 2UH',
    nearestTube: 'Hyde Park Corner / Marble Arch',
    tubeColor: '#003366',
    tubeLineName: 'Piccadilly / Central',
    walkMins: 3,
    cost: 'Free (lido extra)',
    openingHours: 'Daily 5:00–midnight',
    tip: '🎯 The Diana Playground near Kensington Palace is fantastic for under-12s — best play area in London.'
  },
  {
    id: 'greenwich',
    name: 'Greenwich & the Cutty Sark',
    emoji: '🚢',
    category: ['outdoor','attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'Historic Greenwich Park, the Royal Observatory where time began, the Cutty Sark tall ship, and a brilliant market. Take the Thames Clipper for a brilliant river approach.',
    address: 'Greenwich, SE10',
    nearestTube: 'Cutty Sark (DLR)',
    tubeColor: '#00A4A7',
    tubeLineName: 'DLR',
    walkMins: 3,
    cost: 'Park free, Cutty Sark £20 adults / £10 children',
    openingHours: 'Park daily; Cutty Sark 10–17:00',
    tip: '🎯 Take the Thames Clipper from Embankment — the river journey IS the experience.'
  },
  {
    id: 'south-bank',
    name: 'South Bank Walk',
    emoji: '🌉',
    category: ['outdoor','free'],
    free: true,
    ageRange: 'All ages',
    desc: 'Walk from Westminster Bridge to Tower Bridge along the Thames — totally free. Pass the London Eye, Tate Modern, Borough Market, and Southwark Cathedral.',
    address: 'SE1',
    nearestTube: 'Westminster / London Bridge',
    tubeColor: '#003366',
    tubeLineName: 'Jubilee',
    walkMins: 2,
    cost: 'Free',
    openingHours: 'Always open',
    tip: '🎯 The free fountains outside the Royal Festival Hall are brilliant on hot days. Kids run wild!'
  },
  {
    id: 'olympic-park',
    name: 'Queen Elizabeth Olympic Park',
    emoji: '🏟️',
    category: ['outdoor','free'],
    free: true,
    ageRange: 'All ages',
    desc: 'Vast green space with world-class sports venues, playgrounds, cycling, and the ArcelorMittal Orbit tower with the world\'s longest tunnel slide.',
    address: 'Stratford, E20 2ST',
    nearestTube: 'Stratford',
    tubeColor: '#003366',
    tubeLineName: 'Jubilee / Central',
    walkMins: 5,
    cost: 'Park free (Orbit slide £15)',
    openingHours: 'Park always open',
    tip: '🎯 The Tumbling Bay Playground is one of London\'s best — sand, water, climbing. Free!'
  },

  // ── SHOWS & THEATRE ───────────────────────────────────
  {
    id: 'west-end',
    name: 'West End Show',
    emoji: '🎭',
    category: ['show'],
    free: false,
    ageRange: '6+',
    desc: 'Lion King, Hamilton, Matilda, Wicked, Frozen — London\'s West End has the best family musicals in the world. A truly unforgettable experience.',
    address: 'West End, WC2',
    nearestTube: 'Leicester Square / Covent Garden',
    tubeColor: '#003688',
    tubeLineName: 'Piccadilly',
    walkMins: 5,
    cost: '£25–120 (day seats from £20)',
    openingHours: 'Check show schedules',
    tip: '🎯 Check TodayTix and TKTS booth in Leicester Sq for same-day discounted tickets.'
  },
  {
    id: 'covent-garden',
    name: 'Covent Garden & street acts',
    emoji: '🎪',
    category: ['outdoor','free','show'],
    free: true,
    ageRange: 'All ages',
    desc: 'World-class buskers and street performers in the piazza — genuinely some of the best free entertainment in Europe. Juggling, magic, acrobatics daily.',
    address: 'Covent Garden, WC2E 8RF',
    nearestTube: 'Covent Garden',
    tubeColor: '#003688',
    tubeLineName: 'Piccadilly',
    walkMins: 1,
    cost: 'Free (tip the performers!)',
    openingHours: 'Daily from 10:00',
    tip: '🎯 Best performances at 12:30, 14:30, and 16:30 in the main piazza. Get there early for a good spot.'
  },

  // ── DAY TRIPS ─────────────────────────────────────────
  {
    id: 'windsor',
    name: 'Windsor Castle',
    emoji: '👑',
    category: ['attraction'],
    free: false,
    ageRange: '5+',
    desc: 'The world\'s oldest and largest occupied castle — the King\'s weekend home. State Apartments, St George\'s Chapel, and Windsor Great Park nearby.',
    address: 'Windsor, SL4 1NJ',
    nearestTube: 'Windsor & Eton Central (train from Paddington)',
    tubeColor: '#00A0E2',
    tubeLineName: 'Elizabeth line + GWR train',
    walkMins: 5,
    cost: '£32 adults / £17 children',
    openingHours: 'Daily 10–17:15 (16:15 Nov–Feb)',
    tip: '🎯 Catch the Changing of the Guard (11am most days) — check the castle website for dates.'
  },
  {
    id: 'hampton-court',
    name: 'Hampton Court Palace',
    emoji: '🌹',
    category: ['outdoor','attraction'],
    free: false,
    ageRange: 'All ages',
    desc: 'Henry VIII\'s spectacular riverside palace with the famous maze, Tudor kitchens, and gorgeous gardens. A brilliant full-day family trip.',
    address: 'East Molesey, KT8 9AU',
    nearestTube: 'Hampton Court (train from Waterloo)',
    tubeColor: '#E1251B',
    tubeLineName: 'Train from Waterloo (35 min)',
    walkMins: 5,
    cost: '£30 adults / £15 children',
    openingHours: 'Daily 10–17:30',
    tip: '🎯 The maze is the classic — allow 30 mins. Timed ghost tours are amazing in autumn.'
  }
];
